# ===================================
#  Filter Behavior Config
# ===================================

scopes:
    show:
        label: cosmicradiotv.podcast::lang.episode.filter_show
        modelClass: CosmicRadioTV\Podcast\Models\Show
        nameFrom: name
        conditions: show_id in (:filtered)