# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/cosmicradiotv/podcast/models/releasetype/columns.yaml

# Model Class name
modelClass: CosmicRadioTV\Podcast\Models\ReleaseType

# List Title
title: cosmicradiotv.podcast::lang.release_type.list_title

# Link URL for each record
recordUrl: cosmicradiotv/podcast/releasetypes/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: sort_order
    direction: asc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
